server:
  port: 8888
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/precompiler/spring-cloud-101.git
          searchPaths: config-repo
          